#! /bin/bash

export VERSION="47"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="12000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	acpi_call-dkms \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	antimicrox \
	aria2 \
	at \
	bash-completion \
	bat \
	bluez-utils \
	broadcom-wl-dkms \
	bzip2 \
	cage \
	cifs-utils \
	cpupower \
	diffutils \
	dconf-editor \
	dkms \
	distrobox \
	dmidecode \
	dosbox \
	efibootmgr \
	epiphany \
	evtest \
	efibootmgr \
	expect \
	exfatprogs \
	fakeroot \
	fd \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	fzf \
	f2fs-tools \
	git \
	gnome-browser-connector \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-tweaks \
	gnome-shell-extensions \
	gnome-shell-extension-appindicator \
	gnome-shell-extension-desktop-icons-ng \
	gnome-menus \
	gparted \
	gst-plugin-pipewire \
	gvfs-smb \
	gvfs-nfs \
	gzip \
	haveged \
	htop \
	ibus-libpinyin \
	ibus-table-chinese \
	ibus-anthy \
	ibus-hangul \
	ibus-rime \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	imagemagick \
	jq \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-vdpau-driver \
	lib32-mangohud \
	lib32-openal \
	lib32-pipewire \
	lib32-sdl2 \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcec \
	libcurl-gnutls \
	libdisplay-info \
	libidn11 \
	libva-intel-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	loupe \
	lshw \
	lzip \
	mangohud \
	mesa-demos \
	modemmanager \
	mpv \
	nano \
	nautilus \
	networkmanager \
	nfs-utils \
	nmon \
	noto-fonts-cjk \
	noto-fonts-emoji \
	nss-mdns \
	ntfs-3g \
	openal \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	podman \
	poppler \
	pulsemixer \
	python \
	python-pyudev \
	python-systemd \
	papirus-icon-theme \
	qtractor \
	remmina \
	ripgrep \
	rsync \
	screen \
	smartmontools \
	smbclient \
	sof-firmware \
	solaar \
	sshfs \
	steam \
	sudo \
	switcheroo-control \
	s-tui \
	tree \
	tar \
	tree \
	ttf-dejavu \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	v2ray \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-microhei \
	wlr-randr \
	xdelta3 \
	xdg-desktop-portal \
	xdg-desktop-portal-gnome \
	xdg-desktop-portal-wlr \
	xdg-user-dirs-gtk \
	xf86-video-amdgpu \
	xorg-server \
	xorg-server-xvfb \
	xwaylandvideobridge \
	xz \
	yazi \
	zip \
	zoxide \
	zsh \
"

export PACKAGE_OVERRIDES="\
	https://github.com/3003n/linux-chimeraos/releases/download/v6.11.7-sko1-1/linux-chimeraos-6.11.7.sko1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/linux-chimeraos/releases/download/v6.11.7-sko1-1/linux-chimeraos-headers-6.11.7.sko1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-libva-mesa-driver-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-mesa-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-mesa-vdpau-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-opencl-rusticl-mesa-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-vulkan-intel-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-vulkan-mesa-layers-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-vulkan-radeon-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-vulkan-nouveau-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/lib32-vulkan-swrast-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/libva-mesa-driver-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/mesa-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/mesa-vdpau-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/opencl-rusticl-mesa-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/vulkan-intel-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/vulkan-mesa-layers-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/vulkan-radeon-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/vulkan-nouveau-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-chimeraos/releases/download/24.3.0.rc1-chos1-1/vulkan-swrast-1--24.3.0.rc1.chos1-1-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	amdgpu-test-scripts-git \
	anydesk-bin \
	asusctl \
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	boxtron \
	chimeraos-device-quirks-sk-git \
	downgrade \
	edid-decode-git \
	evdev-keepalive \
	frzr-sk \
	gamescope-session-sk-git \
	gamescope-session-steam-git \
	gamescope-session-steam-plus-git \
	gamescope-sk \
	gnome-shell-extension-bluetooth-battery-meter-git \
	gnome-shell-extension-blur-my-shell \
	gnome-shell-extension-dash-to-dock \
	gnome-shell-extension-enhanced-osk-git \
	gnome-shell-extension-hibernate-status-git \
	gnome-shell-extension-screen-autorotate \
	gpd-fan-driver-dkms-git \
	gpdconfig-git \
	hhd \
	hhd-ui \
	hhfc-git \
	hid-msi-claw-dkms-git \
	ibus-pinyin \
	inputplumber-bin \
	kanit-font \
	legendary \
	lib32-extest \
	linux-firmware-valve \
	mission-center \
	moonlight-qt \
	nintendo-udev \
	onedrive-abraunegg \
	paru \
	paruz \
	pikaur \
	powerstation-bin \
	protonup-qt-bin \
	python-pyclip \
	python-vdf \
	r8152-dkms \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	sk-boot-to-windows \
	sk-chos-tool \
	steam_notif_daemon \
	tsukimi-bin \
	waydroid \
	waydroid-script-git \
	yay-git \
	zenergy-dkms-git \
"

export PACKAGES_TO_DELETE="\
	amdvlk \
	clang \
	jack2 \
	lib32-amdvlk \
	lib32-clang \
	openvr \
	pulseaudio \
	pulseaudio-alsa \
"
export OWN_PACKAGES_TO_DELETE=""

export AUR_PACKAGES_TO_DELETE="\
	gamescope-session-git-r*.pkg.tar.zst \
"

export SERVICES="\
	NetworkManager \
	atd \
	avahi-daemon \
	auto-expand-home \
	bluetooth \
	bluetooth-workaround \
	cec-onboot \
	cec-onpoweroff \
	cec-onsleep \
	ds-inhibit \
	fstrim.timer \
	frzr_root-swap-swapfile.swap \
	haveged \
	hostname-fix \
	inputplumber \
	lightdm \
	overlay-backgrounds \
	overlay-fonts \
	overlay-root-home \
	sshd \
	systemd-timesyncd \
	swapfile \
	sk-bind-mount \
	sk-chos-daemon \
	sk-chos-tool-autoupdate.timer \
	sk-setup-kernel-options \
	sk-resume \
"

export USER_SERVICES="\
	pipewire \
	sk-chos-user-daemon \
	sk-first-run-daemon \
	monitor-waydroid \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" >/etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" >/etc/sudoers.d/chimera

	sed -i "s/Defaults secure_path=/# Defaults secure_path=/g" /etc/sudoers

	# sk chimeraos
	echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >"/etc/sudoers.d/${USERNAME}"
	sed -i 's/set mouse=a/set mouse-=a/g' /usr/share/vim/vim*/defaults.vim
	ln -s -f /usr/bin/vim /usr/bin/vi
	sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
	sed -i "s/#SuspendEstimationSec=60min/SuspendEstimationSec=30min/" /etc/systemd/sleep.conf

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook

	remove_packages=(make gcc dkms ${KERNEL_PACKAGE}-headers ardour)
	for package in "${remove_packages[@]}"; do
		pacman --noconfirm -Rnsdd "$package" || true
	done

	# force -steamdeck option in desktop mode to prevent constant steam updates
	# sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/chimera-steam,' /usr/share/applications/steam.desktop

	# Waydroid
	cp /usr/share/applications/Waydroid.desktop /usr/share/applications/Waydroid-Native.desktop
	sed -i 's/Name=Waydroid/Name=Waydroid-Native/g' /usr/share/applications/Waydroid-Native.desktop
	sed -i 's@Exec=waydroid first-launch@Exec=/usr/bin/waydroid-launcher\nX-Steam-Library-Capsule=/usr/share/applications/Waydroid/capsule.png\nX-Steam-Library-Hero=/usr/share/applications/Waydroid/hero.png\nX-Steam-Library-Logo=/usr/share/applications/Waydroid/logo.png\nX-Steam-Library-StoreCapsule=/usr/share/applications/Waydroid/store-logo.png\nX-Steam-Controller-Template=Desktop@g' /usr/share/applications/Waydroid.desktop
	curl -Lo /usr/bin/waydroid-choose-gpu https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh
	chmod +x /usr/bin/waydroid-choose-gpu

	# set permissions for intel_gpu_top and gamescope
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
	setcap 'CAP_SYS_NICE=eip' /usr/bin/gamescope
}
