#! /bin/bash

export VERSION="46"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="10000MB"
export ARCHIVE_DATE="2024/02/15"
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	acpi_call-dkms \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bash-completion \
	bluedevil \
	breeze-gtk \
	broadcom-wl-dkms \
	bzip2 \
	cifs-utils \
	cpupower \
	diffutils \
	dkms \
	discover \
	distrobox \
	dmidecode \
	dosbox \
	dolphin \
	dolphin-plugins \
	efibootmgr \
	ethtool \
	evtest \
	efibootmgr \
	expect \
	exfatprogs \
	falkon \
	fcitx5-im \
	fcitx5-chinese-addons \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	flatpak-kcm \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	f2fs-tools \
	git \
	gnome-disk-utility \
	gst-plugin-pipewire \
	gvfs-smb \
	gzip \
	haveged \
	htop \
	ibus-pinyin \
	ibus-libpinyin \
	ibus-table-chinese \
	ibus-anthy \
	ibus-hangul \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	jq \
	kate \
	kde-gtk-config \
	kdeconnect \
	kdeplasma-addons \
	kfind \
	kgamma \
	kinfocenter \
	konsole \
	kpipewire \
	kscreen \
	ksshaskpass \
	kwallet-pam \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-vdpau-driver \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libretro-beetle-pce-fast \
	libretro-beetle-psx-hw \
	libretro-citra \
	libretro-desmume \
	libretro-dolphin \
	libretro-flycast \
	libretro-genesis-plus-gx \
	libretro-kronos \
	libretro-mesen-s\
	libretro-mgba \
	libretro-mupen64plus-next \
	libretro-nestopia \
	libretro-picodrive \
	libretro-ppsspp \
	libretro-shaders-slang \
	libretro-snes9x \
	libva-intel-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	lshw \
	lzip \
	mesa-demos \
	modemmanager \
	nano \
	networkmanager \
	nfs-utils \
	nmon \
	noto-fonts-emoji \
	nss-mdns \
	ntfs-3g \
	onboard \
	openal \
	openssh \
	p7zip \
	partitionmanager \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	plasma-browser-integration \
	plasma-desktop \
	plasma-disks \
	plasma-nm \
	plasma-pa \
	plasma-thunderbolt \
	plasma-vault \
	plasma-wayland-session \
	podman \
	pulsemixer \
	python \
	python-inotify-simple \
	retroarch \
	rsync \
	screen \
	smartmontools \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	s-tui \
	tree \
	tar \
	tree \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	v2ray \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-microhei \
	xdg-desktop-portal \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-kde \
	xdg-desktop-portal-wlr \
	xf86-video-amdgpu \
	xorg-server \
	xorg-server-xvfb \
	xorg-xinit \
	xsettingsd \
	xz \
	zip \
	zsh \
"

export PACKAGE_OVERRIDES="\
	https://github.com/3003n/linux-chimeraos/releases/download/v6.6.14-chos1-3/linux-chimeraos-6.6.14.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/3003n/linux-chimeraos/releases/download/v6.6.14-chos1-3/linux-chimeraos-headers-6.6.14.chos1-3-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/lib32-libva-mesa-driver-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/lib32-mesa-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/lib32-mesa-vdpau-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/lib32-vulkan-intel-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/lib32-vulkan-radeon-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/libva-mesa-driver-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/mesa-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/mesa-vdpau-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/vulkan-intel-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.0.0-chos1-1/vulkan-radeon-1--24.0.0.chos1-1-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/repos/2023/06/28/extra/os/x86_64/libretro-pcsx2-11900-2-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/l/libretro-mame/libretro-mame-85763-1-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	antimicrox \
	anydesk-bin \
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	bmi260-dkms \
	boxtron \
	chimera \
	downgrade \
	ds-inhibit \
	frzr-sk \
	gamescope-session-steam-git \
	gamescope-session-steam-plus-git \
	gpdconfig-git \
	hhd \
	hhd-user \
	hhfc-git \
	kanit-font \
	legendary \
	lib32-gperftools \
	libretro-dosbox-pure-git \
	libretro-opera-git \
	libretro-prosystem-git \
	libretro-stella2014-git \
	libretro-virtualjaguar-git \
	nintendo-udev \
	opengamepadui-bin \
	opengamepadui-session-git \
	onedrive-abraunegg \
	pikaur \
	powerstation-bin \
	python-pyclip \
	python-vdf \
	protonup-qt-bin \
	r8152-dkms \
	retroarch-autoconfig-udev-git \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl88x2bu-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	steam_notif_daemon \
	steam-removable-media-git \
	wyvern \
	sk-boot-to-windows \
	sk-chos-addon \
	sk-chos-tool \
	waydroid \
	waydroid-script-git \
	yay-bin \
	zenergy-dkms-git \
"

export PACKAGES_TO_DELETE="\
	amdvlk \
	clang \
	jack2 \
	lib32-amdvlk \
	lib32-clang \
	mutter \
	pulseaudio \
	pulseaudio-alsa \
"

export OWN_PACKAGES_TO_DELETE=""

export AUR_PACKAGES_TO_DELETE="\
	gamescope-session-git-r*.pkg.tar.zst \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	auto-expand-home \
	bluetooth \
	bluetooth-workaround \
	ds-inhibit \
	fstrim.timer \
	frzr_root-swap-swapfile.swap \
	handycon \
	haveged \
	hostname-fix \
	lightdm \
	overlay-fonts \
	overlay-root-home \
	powerstation \
	sshd \
	systemd-timesyncd \
	swapfile \
	sk-auto-keep-boot-entry \
	sk-bind-mount \
	sk-chos-daemon \
	sk-chos-tool-autoupdate.timer \
	sk-update-boot-entry \
	sk-resume \
"

export USER_SERVICES="\
	chimera.service \
	pipewire \
	sk-chos-user-daemon \
	sk-first-run-daemon \
	steam-patch.service \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/libretro/autoconfig/udev/Gasia_PS_Gamepad_USB.cfg \
	/usr/share/libretro/autoconfig/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg \
	/usr/share/libretro/autoconfig/udev/Xbox_360_Wireless_Receiver_Chinese01.cfg \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" >/etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" >/etc/sudoers.d/chimera

	# sk chimeraos
	echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >"/etc/sudoers.d/${USERNAME}"
	sed -i 's/set mouse=a/set mouse-=a/g' /usr/share/vim/vim*/defaults.vim
	ln -s -f /usr/bin/vim /usr/bin/vi
	sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
	sed -i "s/#SuspendEstimationSec=60min/SuspendEstimationSec=30min/" /etc/systemd/sleep.conf

	# disable retroarch menu in joypad configs
	find /usr/share/libretro/autoconfig -type f -name '*.cfg' | xargs -d '\n' sed -i '/input_menu_toggle_btn/d'

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook
	pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	rm /usr/bin/dolphin-emu
	rm /usr/bin/dolphin-emu-nogui
	# dolphin-tool is no longer created in new builds?
	#rm /usr/bin/dolphin-tool
	rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop
	# find /usr/share/applications/* | \
	# grep -v anydesk.desktop | \
	# grep -v ca.desrt.dconf-editor.desktop | \
	# grep -v gparted.desktop | \
	# grep -v org.chimeraos.Gamescope.desktop | \
	# grep -v org.chimeraos.app.desktop | \
	# grep -v org.gnome.Console.desktop | \
	# grep -v org.gnome.DiskUtility.desktop | \
	# grep -v org.gnome.FileRoller.desktop | \
	# grep -v org.gnome.Nautilus.desktop | \
	# grep -v org.gnome.Settings.desktop | \
	# grep -v org.gnome.Software.desktop | \
	# grep -v org.gnome.TextEditor.desktop | \
	# grep -v org.gnome.tweaks.desktop | \
	# grep -v org.gnome.Extensions.desktop | \
	# grep -v protonup-qt.desktop | \
	# grep -v steam.desktop | \
	# grep -v sk-chos-tool.desktop | \
	# grep -v sk-chos-tool-command.desktop | \
	# grep -v com.github.tchx84.Flatseal.desktop | \
	# grep -v waydroid.app.install.desktop | \
	# grep -v waydroid.market.desktop | \
	# grep -v Waydroid.desktop | \
	# xargs -I {} sh -c "echo NoDisplay=true >> {}"

	# force -steamdeck option in desktop mode to prevent constant steam updates
	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

	# set permissions for intel_gpu_top and mangohud
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
}
