#! /bin/bash

export VERSION="46-7"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="12000MB"
export ARCHIVE_DATE="2024/05/23"
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-chimeraos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	acpi_call-dkms \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	aria2 \
	at \
	bash-completion \
	bluedevil \
	breeze-gtk \
	broadcom-wl-dkms \
	bzip2 \
	cage \
	cifs-utils \
	cpupower \
	deepin-wallpapers \
	diffutils \
	dkms \
	discover \
	distrobox \
	dmidecode \
	dosbox \
	dolphin \
	dolphin-plugins \
	efibootmgr \
	ethtool \
	evtest \
	efibootmgr \
	expect \
	exfatprogs \
	falkon \
	fcitx5-im \
	fcitx5-chinese-addons \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	flatpak-kcm \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	f2fs-tools \
	git \
	gnome-disk-utility \
	gparted \
	gst-plugin-pipewire \
	gvfs-smb \
	gvfs-nfs \
	gzip \
	haveged \
	htop \
	ibus-libpinyin \
	ibus-table-chinese \
	ibus-anthy \
	ibus-hangul \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	jq \
	kate \
	kde-gtk-config \
	kdeconnect \
	kdeplasma-addons \
	kfind \
	kgamma \
	kinfocenter \
	konsole \
	kpipewire \
	kscreen \
	ksshaskpass \
	kwallet-pam \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-libva \
	lib32-libva-intel-driver \
	lib32-libva-vdpau-driver \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcec \
	libcurl-gnutls \
	libidn11 \
	libva-intel-driver \
	libva-vdpau-driver \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	lshw \
	lzip \
	mesa-demos \
	modemmanager \
	nano \
	networkmanager \
	nfs-utils \
	nmon \
	noto-fonts-emoji \
	nss-mdns \
	ntfs-3g \
	onboard \
	openal \
	openssh \
	p7zip \
	partitionmanager \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	plasma-browser-integration \
	plasma-desktop \
	plasma-disks \
	plasma-nm \
	plasma-pa \
	plasma-thunderbolt \
	plasma-vault \
	podman \
	pulsemixer \
	python \
	python-pyudev \
	python-systemd \
	python-notify2 \
	qtractor \
	rsync \
	screen \
	smartmontools \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	s-tui \
	tree \
	tar \
	tree \
	ttf-dejavu \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	v2ray \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-microhei \
	wlr-randr \
	xdelta3 \
	xdg-desktop-portal \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-kde \
	xdg-desktop-portal-wlr \
	xf86-video-amdgpu \
	xorg-server \
	xorg-server-xvfb \
	xorg-xinit \
	xsettingsd \
	xz \
	zip \
	zsh \
"

export PACKAGE_OVERRIDES="\
	https://ns.switchsystem.eu.org/d/guest/stos/kernel/linux-chimeraos-6.9.2.sk.chos3-1-x86_64.pkg.tar.zst \
	https://ns.switchsystem.eu.org/d/guest/stos/kernel/linux-chimeraos-headers-6.9.2.sk.chos3-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-libva-mesa-driver-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-mesa-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-mesa-vdpau-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-opencl-rusticl-mesa-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-vulkan-intel-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-vulkan-mesa-layers-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-vulkan-radeon-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-vulkan-nouveau-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/lib32-vulkan-swrast-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/libva-mesa-driver-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/mesa-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/mesa-vdpau-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/opencl-rusticl-mesa-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/vulkan-intel-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/vulkan-mesa-layers-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/vulkan-radeon-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/vulkan-nouveau-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
	https://github.com/ChimeraOS/mesa-chimeraos/releases/download/24.1.0-chos1-1/vulkan-swrast-1--24.1.0.chos1-1-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	amdgpu-test-scripts-git \
	antimicrox \
	anydesk-bin \
	asusctl \
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	boxtron \
	downgrade \
	ds-inhibit \
	evdev-keepalive \
	frzr-sk \
	gamescope-session-sk-git \
	gamescope-session-steam-git \
	gamescope-session-steam-plus-git \
	gpd-fan-driver-dkms-git \
	gpdconfig-git \
	hhd \
	hhfc-git \
	ibus-pinyin \
	inputplumber-bin \
	kanit-font \
	legendary \
	lib32-extest \
	linux-firmware-valve \
	mission-center \
	moonlight-qt \
	nintendo-udev \
	onedrive-abraunegg \
	opengamepadui-bin \
	opengamepadui-session-git \
	pikaur \
	plasma5-themes-vapor-steamos \
	powerstation-bin \
	protonup-qt-bin \
	python-pyclip \
	python-vdf \
	r8152-dkms \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl88x2bu-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	sk-boot-to-windows \
	sk-chos-tool \
	steam_notif_daemon \
	waydroid \
	waydroid-script-git \
	yay-bin \
	zenergy-dkms-git \
"

export PACKAGES_TO_DELETE="\
	amdvlk \
	clang \
	jack2 \
	lib32-amdvlk \
	lib32-clang \
	mutter \
	openvr \
	pulseaudio \
	pulseaudio-alsa \
"

export OWN_PACKAGES_TO_DELETE=""

export AUR_PACKAGES_TO_DELETE="\
	gamescope-session-git-r*.pkg.tar.zst \
"

export SERVICES="\
	NetworkManager \
	atd \
	avahi-daemon \
	auto-expand-home \
	bluetooth \
	bluetooth-workaround \
	cec-onboot.service \
	cec-onpoweroff.service \
	cec-onsleep.service \
	ds-inhibit \
	fstrim.timer \
	frzr_root-swap-swapfile.swap \
	haveged \
	hostname-fix \
	inputplumber \
	lightdm \
	overlay-fonts \
	overlay-root-home \
	powerstation \
	sshd \
	systemd-timesyncd \
	swapfile \
	sk-bind-mount \
	sk-chos-daemon \
	sk-chos-tool-autoupdate.timer \
	sk-setup-kernel-options \
	sk-resume \
"

export USER_SERVICES="\
	pipewire \
	sk-chos-user-daemon \
	sk-first-run-daemon \
	monitor-waydroid \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
"

postinstallhook() {
	# Add sudo permissions
	sed -i '/%wheel ALL=(ALL:ALL) ALL/s/^# //g' /etc/sudoers
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/dmidecode -t 11
	" >/etc/sudoers.d/steam
	echo "${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-gamescope
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/bin/chimera-session-use-lightdm
	${USERNAME} ALL=(ALL) NOPASSWD: /usr/share/chimera/bin/power-tool
	" >/etc/sudoers.d/chimera

	# sk chimeraos
	echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >"/etc/sudoers.d/${USERNAME}"
	sed -i 's/set mouse=a/set mouse-=a/g' /usr/share/vim/vim*/defaults.vim
	ln -s -f /usr/bin/vim /usr/bin/vi
	sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config

	# download and add racing wheel udev rules
	pushd /usr/lib/udev/rules.d
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-fanatec-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-logitech-wheel-perms.rules
	curl -L -O https://raw.githubusercontent.com/berarma/oversteer/master/data/udev/99-thrustmaster-wheel-perms.rules
	popd

	# Remove build tools for slimmer image
	rm /usr/share/libalpm/hooks/70-dkms-install.hook
	rm /usr/share/libalpm/hooks/70-dkms-upgrade.hook
	rm /usr/share/libalpm/hooks/71-dkms-remove.hook

	# Remove files from steamdeck-kde-presets
	rm -f /etc/xdg/kcm-about-distrorc || true
	rm -f /etc/xdg/plasma-workspace/env/ibus.sh || true
	rm -f /etc/xdg/autostart/ibus.desktop || true
	rm -f /etc/xdg/autostart/jupiter-plasma-bootstrap.desktop || true
	rm -f /etc/X11/Xsession.d/50rotate-screen || true
	rm -f /etc/sddm.conf.d/steamdeck.conf || true
	rm -f /usr/bin/jupiter-plasma-bootstrap || true

	# pacman --noconfirm -Rnsdd make gcc dkms ${KERNEL_PACKAGE}-headers retroarch ardour

	remove_packages=(make gcc dkms ${KERNEL_PACKAGE}-headers ardour)
	for package in "${remove_packages[@]}"; do
		pacman --noconfirm -Rnsdd "$package" || true
	done

	# remove dolphin standalone emulator files (only need /usr/share/dolphin-emu/sys)
	# rm /usr/bin/dolphin-emu
	# rm /usr/bin/dolphin-emu-nogui
	# dolphin-tool is no longer created in new builds?
	# rm /usr/bin/dolphin-tool
	# rm /usr/share/applications/dolphin-emu.desktop

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop

	# force -steamdeck option in desktop mode to prevent constant steam updates
	# sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/steam-runtime -steamdeck,' /usr/share/applications/steam.desktop

	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/chimera-steam,' /usr/share/applications/steam.desktop

	# Waydroid
	cp /usr/share/applications/Waydroid.desktop /usr/share/applications/Waydroid-Native.desktop
	sed -i 's/Name=Waydroid/Name=Waydroid-Native/g' /usr/share/applications/Waydroid-Native.desktop
	sed -i 's@Exec=waydroid first-launch@Exec=/usr/bin/waydroid-launcher\nX-Steam-Library-Capsule=/usr/share/applications/Waydroid/capsule.png\nX-Steam-Library-Hero=/usr/share/applications/Waydroid/hero.png\nX-Steam-Library-Logo=/usr/share/applications/Waydroid/logo.png\nX-Steam-Library-StoreCapsule=/usr/share/applications/Waydroid/store-logo.png\nX-Steam-Controller-Template=Desktop@g' /usr/share/applications/Waydroid.desktop
	curl -Lo /usr/bin/waydroid-choose-gpu https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh
	chmod +x /usr/bin/waydroid-choose-gpu

	# set permissions for intel_gpu_top and mangohud
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
}
