#!/bin/bash

set -e
set -x

postinstall_download() {
    # pre download some
	pre_path=/usr/local/share/sk-pre
	decky_path=$pre_path/decky
	decky_file=$decky_path/PluginLoader
	decky_version_file=$decky_path/.loader.version
	decky_plugin_path=$pre_path/decky-plugins
	decky_plugin_hhd_path=$pre_path/decky-plugin-hhd
	css_path=$pre_path/css
	css_hhd_path=$pre_path/css-hhd

	zsh_path=$pre_path/zsh

	# pre download decky
	mkdir -p $decky_path
	DECKY_RELEASE=$(curl -s 'https://api.github.com/repos/SteamDeckHomebrew/decky-loader/releases' | jq -r "first(.[])")
	DECKY_VERSION=$(jq -r '.tag_name' <<< ${DECKY_RELEASE} )
	DECKY_DOWNLOADURL=$(jq -r '.assets[].browser_download_url | select(endswith("PluginLoader"))' <<< ${DECKY_RELEASE})
	curl -L $DECKY_DOWNLOADURL --output $decky_file
	echo $DECKY_VERSION > $decky_version_file

	# pre download HHD-Dekcy plugin
	mkdir -p $decky_plugin_hhd_path
	temp_hhd=$(mktemp -d)
	curl -L $(curl -s "https://api.github.com/repos/hhd-dev/hhd-decky/releases/latest" | grep "browser_download_url" | cut -d '"' -f 4) -o $temp_hhd/hhd-decky.tar.gz
	tar -xzvf $temp_hhd/hhd-decky.tar.gz -C $decky_plugin_hhd_path
	rm -rf $temp_hhd

	# pre download decky plugins
	mkdir -p $decky_plugin_path
	temp_decky=$(mktemp -d)
	# PowerControl
	curl -L $(curl -s "https://api.github.com/repos/mengmeet/PowerControl/releases/latest" | grep "browser_download_url" | cut -d '"' -f 4) -o $temp_decky/powercontrol.tar.gz
	tar -xzvf $temp_decky/powercontrol.tar.gz -C $decky_plugin_path
	# HueSync
	curl -L $(curl -s "https://api.github.com/repos/honjow/HueSync/releases/latest" | grep "browser_download_url" | cut -d '"' -f 4) -o $temp_decky/huesync.tar.gz
	tar -xzvf $temp_decky/huesync.tar.gz -C $decky_plugin_path
	# SDH-CssLoader
	curl -L $(curl -s "https://api.github.com/repos/DeckThemes/SDH-CssLoader/releases/latest" | grep "browser_download_url" | cut -d '"' -f 4 | grep "SDH-CSSLoader-Decky.zip") -o $temp_decky/SDH-CSSLoader-Decky.zip
	unzip -o $temp_decky/SDH-CSSLoader-Decky.zip -d $decky_plugin_path
	# ToMoon
	curl -L $(curl -s "https://api.github.com/repos/YukiCoco/ToMoon/releases/latest" | grep "browser_download_url" | cut -d '"' -f 4 | grep "tomoon.*\.zip") -o $temp_decky/tomoon.zip
	unzip -o $temp_decky/tomoon.zip -d $decky_plugin_path

	rm -rf $temp_decky

	# pre download css themes

	# pre download hhd css themes
	mkdir -p $css_hhd_path

	# SBP-ROG-Ally
	# git_url="https://github.com/semakusut/SBP-ROG-Ally.git"
	# git clone --depth 1 $git_url $css_hhd_path/SBP-ROG-Ally
	# sed -i 's/Armoury_Crate.png/Menu.png/g' $css_hhd_path/SBP-ROG-Ally/ally.css

	# SBP-Legion-Go-Theme
	git_url="https://github.com/frazse/SBP-Legion-Go-Theme.git"
	if [ -d $css_hhd_path/SBP-Legion-Go-Theme ]; then
		rm -rf $css_hhd_path/SBP-Legion-Go-Theme
	fi
	git clone --depth 1 $git_url $css_hhd_path/SBP-Legion-Go-Theme
	echo '{"active": true, "Apply": "Legion-Go-Theme"}' > $css_hhd_path/SBP-Legion-Go-Theme/config_USER.json

	# PSBP-PS5-to-Handheld
	git_url="https://github.com/honjow/SBP-PS5-to-Handheld.git"
	if [ -d $css_hhd_path/SBP-PS5-to-Handheld ]; then
		rm -rf $css_hhd_path/SBP-PS5-to-Handheld
	fi
	git clone --depth 1 $git_url $css_hhd_path/SBP-PS5-to-Handheld


	# zsh pre download
	mkdir -p $zsh_path
	git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git $zsh_path/ohmyzsh
	git clone --depth 1 https://github.com/zdharma-continuum/fast-syntax-highlighting "$zsh_path/ohmyzsh/custom/plugins/fast-syntax-highlighting"
	cp $zsh_path/ohmyzsh/templates/zshrc.zsh-template $zsh_path/.zshrc
	sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="ys"/g' $zsh_path/.zshrc
	sed -i 's/plugins=(git)/plugins=(git sudo z fast-syntax-highlighting)/g' $zsh_path/.zshrc


	# 其它操作
	GAMESCOPE_SESSION_PLUS_FILE="/usr/share/gamescope-session-plus/gamescope-session-plus"
	if [[ -f "$GAMESCOPE_SESSION_PLUS_FILE" ]]; then
		# 关闭 gamescope 触摸手势
		sed -i '/export GAMESCOPE_DISABLE_ASYNC_FLIPS/a\\n# disable touch gestures\nexport GAMESCOPE_DISABLE_TOUCH_GESTURES=1' $GAMESCOPE_SESSION_PLUS_FILE
	fi

}